## **Multilayer Perceptron**

In [1]:
# importing the required libraries
import numpy as np

In [2]:
# definning the class of the multi layer perceptron

class MLP():
    # constructor of the mlp class
    def __init__(self,alpha,v,w):
        self.alpha = alpha
        self.v = v
        self.w = w
    # defining the binary sigmoidal activation function
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))
    
    # appending 1 at the index of the argument passed
    # we are appending 1 because we are adding bias to the neuron input
    def append_bias(self,x):
        return np.insert(x,0,1)

    # computing the binary sigmoid derivative
    def sigmoid_derivative(self,x):
        return x*(1-x)

    # function to compute the feed forward from input to hidden layer
    def feed_forward_input_to_hidden(self,x):
        self.z = self.sigmoid(np.matmul(self.v,x))
        self.z = self.append_bias(self.z)
        return self.z

    # function to compute the feedforward from hidden to input layer    
    def feedforward_hidden_to_out(self):
        self.y = self.sigmoid(np.matmul(self.w,self.z))
        return self.y
        
    # computing the error portion of the output layer
    def error_portion(self,t):
        self.error_p = (t-self.y)*self.sigmoid_derivative(self.y)
        return self.error_p
    
    # change of weights between hidden and the output layer
    def compute_dw(self):
        self.dw = self.alpha*(self.error_p*self.z)
        return self.dw

    # error portion of the hidden layer
    def error_portion_hidden(self):
        self.error_p_hidden = []
        for i in range(1,len(self.z)):
            temp = (self.error_p*self.w[i])*self.sigmoid_derivative(self.z[i])
            self.error_p_hidden.append(temp)
        self.error_p_hidden = np.array(self.error_p_hidden)
        return self.error_p_hidden
    
    # change of weights between the hidden and the input layer
    def compute_dv(self,x):
        self.dv = []
        for i in range(len(self.error_p_hidden)):
            temp = self.alpha*self.error_p_hidden[i]*x 
            self.dv.append(temp)
        self.dv = np.array(self.dv)
        return self.dv

    def weight_update(self):
        self.w = self.w + self.dw
        self.v = self.v + self.dv
        return self.w,self.v
  

In [3]:
# assigning the learning rate 
alpha = 0.25

In [4]:
# assigning the weights of the neuron between the input and hidden layer
v = np.array([[0.3,0.6,-0.1],[0.5,-0.3,0.4]])
v

array([[ 0.3,  0.6, -0.1],
       [ 0.5, -0.3,  0.4]])

In [5]:
# assigning the weights of the neuron between the hidden and the output layer
w = np.array([-0.2,0.4,0.1])
w

array([-0.2,  0.4,  0.1])

In [6]:
model = MLP(alpha,v,w)

In [7]:
# creating tensors of x and y
X = np.array([0,1],dtype=np.float32)
T = np.array([1],dtype=np.float32)
X

array([0., 1.], dtype=float32)

In [8]:
X = model.append_bias(X)
X

array([1., 0., 1.], dtype=float32)

In [9]:
# target values
T

array([1.], dtype=float32)

In [10]:
# 1. feed forward from input to hidden layer
model.feed_forward_input_to_hidden(X)

array([1.       , 0.549834 , 0.7109495])

In [11]:
# 2. feed forward from hidden to output layer
model.feedforward_hidden_to_out()

0.5227414361305817

In [12]:
# 3. computing the error portion 
# passing the target variable to the function
model.error_portion(T)

array([0.11906782], dtype=float32)

In [13]:
# 4. finding the change of weights : dw
model.compute_dw()

array([0.02976695, 0.01636688, 0.0211628 ])

In [14]:
# 5. computing the error portion of the hidden layer
model.error_portion_hidden()

array([[0.0117885 ],
       [0.00244685]], dtype=float32)

In [15]:
# 6. computing the change of weights between the hidden and the input layer : dv
model.compute_dv(X)

array([[0.00294713, 0.        , 0.00294713],
       [0.00061171, 0.        , 0.00061171]], dtype=float32)

In [16]:
# 7. updating the weights 
w,v = model.weight_update()

In [17]:
# updated w 
w

array([-0.17023305,  0.41636688,  0.1211628 ])

In [18]:
# updated v
v

array([[ 0.30294713,  0.6       , -0.09705287],
       [ 0.50061171, -0.3       ,  0.40061171]])