### **Building a Multilayer Perceptron and trainning it with backpropagation algorithm**

In [1]:
# importing the required libraries
import numpy as np

In [2]:
# definning the class of the multi layer perceptron

class MLP():
    # constructor of the mlp class
    def __init__(self,alpha,v,w):
        self.alpha = alpha
        self.v = v
        self.w = w
    # defining the binary sigmoidal activation function
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))
    
    # appending 1 at the index of the argument passed
    # we are appending 1 because we are adding bias to the neuron input
    def append_bias(self,x):
        return np.insert(x,0,1)

    # computing the binary sigmoid derivative
    def sigmoid_derivative(self,x):
        return x*(1-x)

    # function to compute the feed forward from input to hidden layer
    def feed_forward_input_to_hidden(self,x):
        self.z = self.sigmoid(np.matmul(self.v,x))
        self.z = self.append_bias(self.z)
        return self.z

    # function to compute the feedforward from hidden to input layer    
    def feedforward_hidden_to_out(self):
        self.y = self.sigmoid(np.matmul(self.w,self.z))
        return self.y
        
    # computing the error portion of the output layer
    def error_portion(self,t):
        self.error_p = (t-self.y)*self.sigmoid_derivative(self.y)
        return self.error_p
    
    # change of weights between hidden and the output layer
    def compute_dw(self):
        self.dw = self.alpha*(self.error_p*self.z)
        return self.dw

    # error portion of the hidden layer
    def error_portion_hidden(self):
        self.error_p_hidden = []
        for i in range(1,len(self.z)):
            temp = (self.error_p*self.w[i])*self.sigmoid_derivative(self.z[i])
            self.error_p_hidden.append(temp)
        self.error_p_hidden = np.array(self.error_p_hidden)
        return self.error_p_hidden
    
    # change of weights between the hidden and the input layer
    def compute_dv(self,x):
        self.dv = []
        for i in range(len(self.error_p_hidden)):
            temp = self.alpha*self.error_p_hidden[i]*x 
            self.dv.append(temp)
        self.dv = np.array(self.dv)
        return self.dv

    def weight_update(self):
        self.w = self.w + self.dw
        self.v = self.v + self.dv
        return self.w,self.v

In [3]:
def train(model,X,T,epocs=5):
  cost=[]
  for epoch in range(epocs):
    yexp=[]
    for i in range(len(X)):
      # 1. feed forward from input to hidden layer
      model.feed_forward_input_to_hidden(X)

      # 2. feed forward from hidden to output layer
      yhat = model.feedforward_hidden_to_out()

      # 3. computing the error portion
      model.error_portion(T)
        
      # 4. finding the change of weights : dw
      model.compute_dw()

      # 5. computing the error portion of the hidden layer
      model.error_portion_hidden()

      # 6. computing the change of weights between the hidden and the input layer : dv
      model.compute_dv(X)

      # 7. updating the weights
      model.weight_update()
      yexp.append(yhat)
    print("Epoch",epoch,":",yhat)
    

In [4]:
# assigning the learning rate 
alpha = 1.0

In [5]:
# assigning the weights of the neuron between the input and hidden layer
v = np.array([[0.3,0.6,-0.1],[0.5,-0.3,0.4]])
v

array([[ 0.3,  0.6, -0.1],
       [ 0.5, -0.3,  0.4]])

In [6]:
# assigning the weights of the neuron between the hidden and the output layer
w = np.array([-0.2,0.4,0.1])
w

array([-0.2,  0.4,  0.1])

In [7]:
model = MLP(alpha,v,w)

In [8]:
# creating tensors of x and y
X = np.array([0,1],dtype=np.float32)
T = np.array([1],dtype=np.float32)
X

array([0., 1.], dtype=float32)

In [9]:
X = model.append_bias(X)
X

array([1., 0., 1.], dtype=float32)

In [10]:
# target values
T

array([1.], dtype=float32)

In [11]:
train(model,X,T,epocs=50)

Epoch 0 : 0.6225246377668144
Epoch 1 : 0.717972793442314
Epoch 2 : 0.7734275573992476
Epoch 3 : 0.8085876684073626
Epoch 4 : 0.8327646641513959
Epoch 5 : 0.8504453429672344
Epoch 6 : 0.8639846867704015
Epoch 7 : 0.8747230501301559
Epoch 8 : 0.8834763760772626
Epoch 9 : 0.890769302927056
Epoch 10 : 0.8969545965769304
Epoch 11 : 0.902278392939364
Epoch 12 : 0.90691782945573
Epoch 13 : 0.9110037761793701
Epoch 14 : 0.9146351199084393
Epoch 15 : 0.9178880505770097
Epoch 16 : 0.9208222757683592
Epoch 17 : 0.9234852922645259
Epoch 18 : 0.9259153885797113
Epoch 19 : 0.9281437956145406
Epoch 20 : 0.9301962623486634
Epoch 21 : 0.9320942217686405
Epoch 22 : 0.9338556704375143
Epoch 23 : 0.9354958392288909
Epoch 24 : 0.93702771109221
Epoch 25 : 0.938462429930906
Epoch 26 : 0.9398096157593697
Epoch 27 : 0.9410776238378684
Epoch 28 : 0.9422737463783419
Epoch 29 : 0.9434043810682603
Epoch 30 : 0.9444751640393952
Epoch 31 : 0.9454910840418129
Epoch 32 : 0.9464565726997348
Epoch 33 : 0.947375582142445